### ISSUE TITLE
rust-9999 fails at src_install phase.

### ISSUE THREAD

**Issue by o01eg** [gentoo/gentoo-rust#230] opened 2017-02-15 19:23 UTC
This PR (https://github.com/rust-lang/rust/pull/39728) introduced new error:
```
running: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "--force" "--verbose" "--debug" "--ver
s" "0.1.4" "cargo-vendor"
^O     Running^O `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name libgit2_sys /tmp/portage/dev-lang/rust-9999/homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.6/lib.rs --crate-type lib -g --cfg feature=\"https\" --cfg feature=\"ssh\" --cfg feature=\"curl\" --cfg feature=\"curl-sys\" --cfg feature=\"openssl-sys\" --cfg feature=\"libssh2-sys\" -C metadata=55dc646ad12fdaeb -C extra-filename=-55dc646ad12fdaeb --out-dir /tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --emit=dep-info,link -L dependency=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --extern libssh2_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibssh2_sys-1c8426da8efdab7a.rlib --extern curl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libcurl_sys-1838572cde66848e.rlib --extern openssl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libopenssl_sys-e89179dab904d606.rlib --extern libz_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibz_sys-57beb9d53e752aa8.rlib --extern libc=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibc-83c2bd88b43ecde3.rlib --cap-lints allow -L native=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/build/libgit2-sys-294bff880f16dcf0/out/lib -l static=git2 -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64`
error^O: could not find native static library `git2`, perhaps an -L flag is missing?^O

^OBuild failed, waiting for other jobs to finish...
^O^Oerror:^O failed to compile `cargo-vendor v0.1.4`, intermediate artifacts can be found at `/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj`
^O
Caused by:
^O^O  Could not compile `libgit2-sys`.
^O^O
Caused by:
^O^O  process didn't exit successfully: `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name libgit2_sys /tmp/portage/dev-lang/rust-9999/homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.6/lib.rs --crate-type lib -g --cfg feature="https" --cfg feature="ssh" --cfg feature="curl" --cfg feature="curl-sys" --cfg feature="openssl-sys" --cfg feature="libssh2-sys" -C metadata=55dc646ad12fdaeb -C extra-filename=-55dc646ad12fdaeb --out-dir /tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --emit=dep-info,link -L dependency=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --extern libssh2_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibssh2_sys-1c8426da8efdab7a.rlib --extern curl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libcurl_sys-1838572cde66848e.rlib --extern openssl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libopenssl_sys-e89179dab904d606.rlib --extern libz_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibz_sys-57beb9d53e752aa8.rlib --extern libc=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibc-83c2bd88b43ecde3.rlib --cap-lints allow -L native=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/build/libgit2-sys-294bff880f16dcf0/out/lib -l static=git2 -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64` (exit code: 101)
^O

command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "--force" "--verbose" "--debug" "--vers" "0.1.4" "cargo-vendor"
expected success, got: exit code: 101
```

I check `/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/build/libgit2-sys-294bff880f16dcf0/out/lib` directory but it doesn't exists. The parent folder contains only `build` directory which contains required file:
```
oleg rust # ls /tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/build/libgit2-sys-294bff880f16dcf0/out/build/
CMakeCache.txt  CMakeFiles  cmake_install.cmake  install_manifest.txt  libgit2.a  libgit2.pc  Makefile
```

**Comment by ishitatsuyuki** [comment] 2017-02-26 02:42
Can also reproduce on Arch PKGBUILD too. The reason remains unknown.

**Comment by TyanNN** [comment] 2017-02-27 15:43
Can confirm, it's probably caused by not including `dev-libs/libgit2` in DEPEND section?

**Comment by TyanNN** [comment] 2017-03-03 07:23
Can also confirm on Funtoo

**Comment by TyanNN** [comment] 2017-03-04 19:57
It seems like the issue is fixed by adding `emake dist` after first emake in `src_install()`

**Closed** 2017-03-04 21:57 UTC
