### ISSUE TITLE
The `rust-bin-9999` ebuild attempts to fetch bogus URL

### ISSUE THREAD

**Issue by ArniDagur** [gentoo/gentoo-rust#421] opened 2019-07-27 22:42 UTC
```
[arni][/etc/portage/package.use]% sudo emerge -a dev-lang/rust-bin:nightly

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  NS    ] dev-lang/rust-bin-9999 [1.36.0] USE="-rls% -rustlib_targets_wasm32-unknown-unknown%"

Would you like to merge these packages? [Yes/No] y

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-lang/rust-bin-9999::rust
>>> Unpacking source...
--2019-07-26 23:50:53--  https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.xz
Resolving static.rust-lang.org... 13.224.227.30, 13.224.227.39, 13.224.227.58, ...
Connecting to static.rust-lang.org|13.224.227.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 265358708 (253M) [application/x-tar]
Saving to: ‘rust-nightly-x86_64-unknown-linux-gnu.tar.xz’

rust-nightly-x86_64 100%[===================>] 253.07M  49.9MB/s    in 6.5s

2019-07-26 23:51:00 (38.8 MB/s) - ‘rust-nightly-x86_64-unknown-linux-gnu.tar.xz’ saved [265358708/265358708]

>>> Unpacking ./rust-nightly-x86_64-unknown-linux-gnu.tar.xz to /sdb/var/tmp/portage/dev-lang/rust-bin-9999/work
 * Adding ...
--2019-07-26 23:51:11--  https://static.rust-lang.org/dist/rust-std-nightly-.tar.xz
Resolving static.rust-lang.org... 13.224.227.103, 13.224.227.30, 13.224.227.39, ...
Connecting to static.rust-lang.org|13.224.227.103|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-26 23:51:11 ERROR 404: Not Found.

 * ERROR: dev-lang/rust-bin-9999::rust failed (unpack phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 125:  Called src_unpack
 *   environment, line 1363:  Called die
 * The specific snippet of code:
 *           wget "${MY_STDLIB_SRC_URI}-${target}.tar.xz" || die;
 *
 * If you need support, post the output of `emerge --info '=dev-lang/rust-bin-9999::rust'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/rust-bin-9999::rust'`.
 * The complete build log is located at '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/temp/build.log'.
 * The ebuild environment file is located at '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/temp/environment'.
 * Working directory: '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/work'
 * S: '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/work/rust-bin-9999'

>>> Failed to emerge dev-lang/rust-bin-9999, Log file:

>>>  '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/temp/build.log'

 * Messages for package dev-lang/rust-bin-9999:

 * Adding ...
 * ERROR: dev-lang/rust-bin-9999::rust failed (unpack phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 125:  Called src_unpack
 *   environment, line 1363:  Called die
 * The specific snippet of code:
 *           wget "${MY_STDLIB_SRC_URI}-${target}.tar.xz" || die;
 *
 * If you need support, post the output of `emerge --info '=dev-lang/rust-bin-9999::rust'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/rust-bin-9999::rust'`.
 * The complete build log is located at '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/temp/build.log'.
 * The ebuild environment file is located at '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/temp/environment'.
 * Working directory: '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/work'
 * S: '/sdb/var/tmp/portage/dev-lang/rust-bin-9999/work/rust-bin-9999'
```

**Comment by stefson** [comment] 2019-07-28 05:17
Yeah, I noticed that as well. Still couldn't find the reason.

**Comment by temporary-username-largedicks** [comment] 2019-08-05 23:11
The problem is this part in src_unpack:

	for arch in ${ALL_RUSTLIB_TARGETS}; do
		use ${arch} && target=${arch#"rustlib_targets_"}
		elog "Adding ${target}..."
		wget "${MY_STDLIB_SRC_URI}-${target}.tar.xz" || die
		unpack ./"rust-std-nightly-${target}.tar.xz"
		mv "${WORKDIR}/rust-std-nightly-${target}/rust-std-${target}" "${S}/" || die
		cat "${WORKDIR}/rust-std-nightly-${target}/components" >> "${S}/components"
	done

For whatever reason the `target` variable can end up being empty in which case it attempts to fetch a malformed uri; I simply added `[  "$target" ] || continue`  after the line that sets target right now as a quick and dirty fix which stops the problem on my system and emerges it just fine.

**Comment by temporary-username-largedicks** [comment] 2019-08-06 03:36
I see the problem now and what it does wrongly; it should obviously be:

	for arch in ${ALL_RUSTLIB_TARGETS}; do
		if use ${arch}; then
			target=${arch#"rustlib_targets_"}
			elog "Adding ${target}..."
			wget "${MY_STDLIB_SRC_URI}-${target}.tar.xz" || die
			unpack ./"rust-std-nightly-${target}.tar.xz"
			mv "${WORKDIR}/rust-std-nightly-${target}/rust-std-${target}" "${S}/" || die
			cat "${WORKDIR}/rust-std-nightly-${target}/components" >> "${S}/components"
		fi
	done
}

As in it should only do that entire step there if it actually uses that specific arch.

**Comment by stefson** [comment] 2019-08-06 09:42
a pullrequest with a fix for this would be highly appreciated.

**Comment by temporary-username-largedicks** [comment] 2019-08-06 09:48
> a pullrequest with a fix for this would be highly appreciated.

It'd be highly appreciated if you and all the other pullreqfags get a.i.d.s. from being raped by a gorilla and sod of and die.

It's a simple fucking edit, you troglodyte fagarse; the fuck do you expect me to seriously make a pullreq over that because all you fucking faggots wants is do everything with your asinine pullreqs — fuck you; take a chainsaw to the face; I hope you get forced to watch your children raped because if they haven't committed suicide by now from your existence alone they deserve it anyway. Go bother someone else, fuck off and just die with your bullshit "pullrequæst" for such a trivial fucking change. If I could legally put a chainsaw to your face I would.

**Comment by stefson** [comment] 2019-08-06 09:50
You're wrong. It's a copyright issue.

**Comment by temporary-username-largedicks** [comment] 2019-08-06 09:55
I'm pretty sure such a trivial change qualifies not for copyright and since the fix is pretty much identifying the bug and after which the change becomes trivial I'm sure you can find a different implementation if you must because it's a trivial fix after the the bug has been identified.

Having said that I herewith dedicate each and every single idea and implementation that I made in this discussion to the irrevocably to the public domain and renounce any intellectual and moral rights I might have to them to the fullest extent possible. Also any legal officer that ever gets to review this is a fag that should get fucked with a screwdriver through the eyeball to further bias them in favor of the other party if you need that extra insurance.

**Comment by stefson** [comment] 2019-08-06 10:03
Well, if you're not interested into your 15 minutes of fame, someone™ is going to pick this up at some point in the future.

**Comment by temporary-username-largedicks** [comment] 2019-08-06 10:10
Yeah like you, maybe — this change is so fucking trivial it can easily just be edited manually by whatever developer having commit rights.

Besides — I know not even how git works and how to make one; I've never used it in my life.

**Comment by stefson** [comment] 2019-08-06 10:24
Don't bother with learning git, if you don't even get it that everyone's got commit rights through pullrequests. Also please take up some yoga, I'm sure you're going to find it benificial. If that doesn't help, you're free to leave, I'm sure we'll manage without you. Even though I find this kind of hilarious :-)

**Comment by stefson** [comment] 2019-08-26 09:53
If it's fixed please close, thanks.

**Closed** 2019-08-26 12:04 UTC
